// Application Component
export const APPLICATION_COMPONENT_CREATED = 'APPLICATION_COMPONENT_CREATED';
export const APPLICATION_COMPONENT_UPDATED = 'APPLICATION_COMPONENT_UPDATED';
export const APPLICATION_COMPONENT_DELETED = 'APPLICATION_COMPONENT_DELETED';

// Common
export const ITEM_SELECTED = 'ITEM_SELECTED';
